name: todoappp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
  intl: any
  google_fonts: ^5.1.0
  provider: ^6.1.2
  easy_date_timeline: ^1.0.3
  flutter_slidable: ^3.1.1


 
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
flutter_native_splash:
  background_image: assets/images/splash-light.png
  background_image_dark: assets/images/splash-dark.png
  android_12:
    color: "#DFECDB"
    color_dark: "0601E1"
    image: assets/images/logo.png
    branding: assets/images/branding.png
  android: true
  web: true
  ios: true


  
flutter_lints: ^4.0.0




flutter:
  generate: true

  
  uses-material-design: true

  assets:
     - assets/images/logo.png
     - assets/images/splash-light.png
     - assets/images/splash-dark.png
     - assets//images/branding.png